CREATE DATABASE product_db;

USE product_db;

CREATE TABLE products
(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(256) NOT NULL ,
    price DECIMAL(20, 2) NOT NULL DEFAULT 0.00,
    description VARCHAR(1000) NULL ,
    quantity INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE = InnoDB;